name: 漏洞反馈
description: 报告一个漏洞
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## 在开始之前

        🚨 **请务必按以下步骤操作** 🚨

        1. 请确保在创建问题前更新仓库，运行以下任一命令：
           - `.\git\bin\git.exe pull`
           - `.\PortableGit\bin\git.exe pull`
           - `git pull`
           
        2. 检查是否已有类似问题存在。

        3. 请尽可能提供详细信息，包括崩溃日志（如有）。
  - type: textarea
    validations:
      required: true
    attributes:
      label: 版本信息
      description: |
        请提供 BallonsTranslator 的版本信息。请复制控制台显示的以下内容（如果信息消失，请保存项目并重启程序）：
        - Python 版本及解释器路径
        - 应用版本、分支及 Commit Hash
      placeholder: |
        示例:
        py version: 3.10.9 (tags/v3.10.9:...)
        py executable: 路径\到\解释器
        version: 1.4.0
        branch: dev
        Commit hash: 53eee46fd7bef117a4ada9a86843c3bf6e37d953
  - type: textarea
    validations:
      required: true
    attributes:
      label: 问题描述
      description: |
        请详细描述问题，并提供复现步骤。
  - type: textarea
    attributes:
      label: 屏幕截图
      description: |
        如果可能，请附上错误时的屏幕截图（可直接拖拽图片）。
  - type: textarea
    attributes:
      label: 日志
      description: |
        请复制粘贴日志内容（内容会自动格式化为代码块）。
  - type: textarea
    attributes:
      label: 其他信息
      description: |
        其他你想提供的信息。
