name: 漏洞反馈 / Bug Report
description: 报告一个漏洞 / Report a bug
labels: [bug 🐛]
body:
  - type: markdown
    attributes:
      value: |
        ## 在开始之前 / Before you begin
        
        🚨 **请勿略过说明 / Please do not skip instructions** 🚨

        1. 请确保在打开一个新议题之前，查找并确认不要与已有议题重复。
           
           Please make sure to look for existing issues before opening a new one.

        2. 请尽可能多地提供信息，包括崩溃日志（如果适用）。
           
           Please provide as much information as possible, including crash logs if applicable.
  
  - type: textarea
    validations:
      required: true
    attributes:
      label: 版本信息 / Version Info
      description: |
        请提供 BallonsTranslator 的版本信息。你可以复制下面的示例文本（或附上截图），确保包含以下内容：
        - Python 版本及解释器路径
        - 应用版本、分支及 Commit Hash
      placeholder: |
        py version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
        py executable: G:\Ballon-translator-portable-main\venv\Scripts\python.exe
        version: 1.4.0
        branch: dev
        Commit hash: 53eee46fd7bef117a4ada9a86843c3bf6e37d953
      render: shell

  - type: textarea
    validations:
      required: true
    attributes:
      label: 问题描述 / Description of the problem
      description: |
        请详细描述这个漏洞，并提供复现步骤。
        Describe the bug in detail and provide reproduction steps.
  
  - type: textarea
    attributes:
      label: 屏幕截图 / Screenshot
      description: |
        如果可以，请附上发生错误时的屏幕截图。你可以直接拖拽图片到文本框。
        If possible, attach a screenshot when the error occurred.
  
  - type: textarea
    attributes:
      label: 日志 / Logs
      description: |
        请复制粘贴日志内容，它们会自动格式化为代码块。
        Paste logs here; they will be auto-formatted as a code block.
      render: shell

  - type: textarea
    attributes:
      label: 其他信息 / Additional Information
      description: |
        任何你想提供的其他信息。
        Any additional information you would like to provide.
