name: 功能建议 / Feature Request
description: 提出你希望软件实现的新功能或优化 / Propose new features or optimizations
labels: [feature ✨]
body:
  - type: markdown
    attributes:
      value: |
        ## 在开始之前 / Before you begin
        
        🚨 **请勿略过说明 / Please do not skip instructions** 🚨

        1. 请确保在打开一个新议题之前，查找并确认不要与已有议题重复。
           
           Please make sure to look for existing issues before opening a new one.
  
  - type: textarea
    validations:
      required: true
    attributes:
      label: 版本信息 / Version Info
      description: |
        请提供 BallonsTranslator 的版本信息。你可以复制下面的示例文本（或附上截图），确保包含以下内容：
        - Python 版本及解释器路径
        - 应用版本、分支及 Commit Hash
      placeholder: |
        py version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
        py executable: G:\Ballon-translator-portable-main\venv\Scripts\python.exe
        version: 1.4.0
        branch: dev
        Commit hash: 53eee46fd7bef117a4ada9a86843c3bf6e37d953
      render: shell

  - type: dropdown
    validations:
      required: true
    attributes:
      label: 建议类型 / Type of request
      options:
        - 新功能 / New feature
        - 功能优化 / Optimization of feature

  - type: textarea
    validations:
      required: true
    attributes:
      label: 描述 / Description
      description: |
        请详细描述你希望添加或改进的功能。
        Describe the feature or improvement you would like to see.
  
  - type: textarea
    attributes:
      label: 图片 / Pictures
      description: |
        如果可以，请附上相关示例或界面截图。你可以直接拖拽图片到文本框。
        If possible, attach relevant examples or UI screenshots.
  
  - type: textarea
    attributes:
      label: 其他信息 / Additional Information
      description: |
        任何你想提供的其他信息。
        Any additional information you would like to provide.
